#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 23 14:10:53 2018

@author: afleischer
"""

import os
import time
import string

start_time = time.time()

direct = '/'+ os.path.join('Users', 'afleischer', 'Lambada_Matcher')

passage_dict = {}
matched_list = []
train_tracks = []

#trains = open('train.txt' , 'r', encoding='utf-8')
#for line in trains.readlines():
#    train_tracks.append(line[12:].strip('\n'))
#trains.close()
#print(train_tracks)

for root, dirs, filenames in os.walk(direct):
    for folder in dirs:
        subdirect = os.path.join(direct, folder)
        for root, dirs, filenames in os.walk(subdirect):
            for file in filenames:
                if file.endswith('.txt'):
                    passage_counter = 0
                    reader = open(os.path.join(subdirect,file), 'r', encoding='UTF-8')
                    try:
                        for line in reader.readlines():
                            passage_dict[line.lower().strip('\n')] = (os.path.join(subdirect, file), passage_counter)
                            passage_counter += 1
                        reader.close()
                    except UnicodeDecodeError:
                        pass
        
        
                


l_dev = open('lambada_untok_test.txt', 'r', encoding='UTF-8')

for line in l_dev.readlines():
    matched_list.append(passage_dict.get(line, "Youse talkin to me?"))
    

print(matched_list)
print(time.time() - start_time)
    
